language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server

cache: yarn

stages:
  - name: Lint
  - name: TS Build
    # - name: Unit Tests
    # - name: Docker Build
    # - name: Docker Push

jobs:
  include:
    - stage: Lint
      install: yarn
      script: yarn lint
    - stage: TS Build
      before_install: cd client
      install: yarn
      script: yarn build
    - stage: TS Build
      before_install: cd server
      install: yarn
      script: yarn build



      # script:
      #   - cd /$TRAVIS_BUILD_DIR/$TEST_SUITE
      #   - yarn
      #   - yarn lint
      #   - yarn build
      #   - yarn test
      #
      # jobs:
      #   include:
      #     - stage: docker_push
      #       name: "Push to Docker Registry"
      #       env:
      #         - TEST_SUITE=client
      #       script: 
      #         - cd /$TRAVIS_BUILD_DIR
      #         - node -e 'console.log("deploy time!")' $TEST_SUITE
