language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server

cache: yarn

script:
  - cd /$TRAVIS_BUILD_DIR/$TEST_SUITE
  - yarn
  - yarn lint
  - yarn build
  - yarn test

stages:
  - name: Test
  - name: Build and Push Container

jobs:
  include:
    - stage: Build and Push Container
      name: "Build client container"
      before_install: cd /$TRAVIS_BUILD_DIR/client
      script: echo "docker build" $TRAVIS_TAG
    - stage: Build and Push Container
      name: "Build server container"
      before_install: cd /$TRAVIS_BUILD_DIR/server
      script: echo "docker build" $TRAVIS_TAG



      #
      # jobs:
      #   include:
      #     - stage: docker_push
      #       name: "Push to Docker Registry"
      #       env:
      #         - TEST_SUITE=client
      #       script: 
      #         - cd /$TRAVIS_BUILD_DIR
      #         - node -e 'console.log("deploy time!")' $TEST_SUITE
