language: node_js
node_js:
  - 8
  - 10

matrix:
  allowed_failures:
    - node_js: 8
install:
  - cd server
  - yarn
  - yarn build
  - cd ../client
  - yarn
  - cd ../

cache: yarn

script:
  - cd server
  - yarn lint && yarn test:cov
  - cd ../client
  - yarn lint && yarn test
