language: node_js
node_js:
  - 8
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server

matrix:
  allowed_failures:
    - node_js: 8
install:
  - cd $TEST_SUITE
  - yarn

cache: yarn

script:
  - cd $TEST_SUITE
  - yarn build
  - yarn lint && yarn test
