language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server

cache: yarn

script:
  - cd /$TRAVIS_BUILD_DIR/$TEST_SUITE
  - yarn
  - yarn lint
  - yarn build
  - yarn test

stages:
  - name: Test
  - name: Build and Push Container
  - name: Notify Slack
  - name: Server Side

jobs:
  include:
    - stage: Build and Push Container
      name: "Build Client Container"
      before_install: cd /$TRAVIS_BUILD_DIR/client
      script: 
        - echo "docker build" $TRAVIS_TAG
        - echo $TRAVIS_TEST_RESULT

    - stage: Build and Push Container
      name: "Build Server Container"
      before_install: cd /$TRAVIS_BUILD_DIR/server
      script: 
       - echo "docker build" $TRAVIS_TAG
       - echo $TRAVIS_TEST_RESULT

    - stage: Notify Slack
      name: "Let slack know what's passed"
      script: echo "notify slack"
