language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server
  - ACTION=lint
  - ACTION=build
  - ACTION=test

cache: yarn

script:
  - cd /$TRAVIS_BUILD_DIR/$TEST_SUITE
  - yarn
  - yarn $ACTION

stages:
  - name: Build Container
  - name: Push Container

jobs:
  include:
    - stage: Build Container
      name: "Build client container"
      before_install: cd /$TRAVIS_BUILD_DIR/client
      script: echo "docker build" $TRAVIS_TAG
    - stage: Build Container
      name: "Build server container"
      before_install: cd /$TRAVIS_BUILD_DIR/server
      script: echo "docker build" $TRAVIS_TAG



      #
      # jobs:
      #   include:
      #     - stage: docker_push
      #       name: "Push to Docker Registry"
      #       env:
      #         - TEST_SUITE=client
      #       script: 
      #         - cd /$TRAVIS_BUILD_DIR
      #         - node -e 'console.log("deploy time!")' $TEST_SUITE
