language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=client
  - TEST_SUITE=server

install:
  # This sets the context for the whole thing
  - cd $TEST_SUITE
  - yarn

cache: yarn

script:
  - yarn build
  - yarn lint && yarn test

jobs:
  include:
    - stage: deploy
      env:
        - TEST_SUITE=client
        - TEST_SUITE=server
      script: 
        - cd $TEST_SUITE
        - node -e 'console.log("deploy time!")' $TEST_SUITE
